import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import promise from 'eslint-plugin-promise';
import security from 'eslint-plugin-security';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import nextPlugin from '@next/eslint-plugin-next';

/**
 * Package boundaries (section 26).
 *
 * The canonical inventory domain must stay free of UI, framework, provider
 * transport, and database concerns so its rules can be reasoned about and
 * property-tested in isolation. These are enforced with no-restricted-imports
 * rather than a resolver-dependent plugin, so the check works without needing
 * module resolution to succeed and cannot be silently skipped.
 */
const FRAMEWORK_AND_IO = [
  { group: ['next', 'next/*'], message: 'Framework imports are not allowed here.' },
  { group: ['react', 'react-dom', 'react/*'], message: 'UI imports are not allowed here.' },
  {
    group: ['pg', 'drizzle-orm', 'drizzle-orm/*'],
    message: 'Database imports are not allowed here.',
  },
  {
    group: ['node:fs', 'node:fs/*', 'node:net', 'node:http', 'node:https'],
    message: 'Direct I/O is not allowed here.',
  },
];

/**
 * No automatic path to a reviewed operation (sections 3, 30).
 *
 * Milestone 5's exit gate requires that "no auto-publication/recurring-price
 * path exists". A test can show that nothing currently publishes by itself; only
 * this can show that nothing can be made to. The automatic tier — the scheduler,
 * the queue, and the worker that drains it — cannot import the packages that
 * publish listings, change prices, copy orders, or spend a business's money on
 * postage, so wiring one into a background job is a build failure rather than a
 * code review somebody has to catch.
 *
 * The dependency runs the other way and always will: a reviewed operation may
 * enqueue work, and does. What it must never be is something work can enqueue.
 *
 * `@eim/review` is deliberately not on this list. It is the gate itself and can
 * carry nothing out — no provider call lives in it — so a background job may use
 * it to expire proposals nobody confirmed, which is exactly the kind of work a
 * background job should be doing. Splitting the gate away from the operations
 * was what made that distinction expressible.
 */
const NO_REVIEWED_OPERATIONS = {
  group: ['@eim/listings', '@eim/listings/*', '@eim/shipping', '@eim/shipping/*'],
  message:
    'Reviewed operations are confirmed by a person, never scheduled. Section 3 excludes automatic publication and recurring price synchronization from version 1, and section 30 requires a confirmed cost preview before any label purchase.',
};

const restrict = (patterns) => ({
  'no-restricted-imports': ['error', { patterns }],
});

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      // A deployment that serves from .next also has the release being built
      // and the one it replaced sitting beside it. Both are build output, and
      // linting compiled chunks fails outright rather than merely wasting time,
      // because the type-aware rules have no tsconfig covering them.
      '**/.next.build/**',
      '**/.next.old/**',
      '**/coverage/**',
      '**/drizzle/**',
      // Plain-JavaScript config files. They are outside every tsconfig, so the
      // type-aware rules have no program to consult and error rather than
      // skipping the file.
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.cjs',
      // Generated by Next.js on every build.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,

  // Type-aware linting across every TypeScript file. strictTypeChecked is the
  // point of choosing typescript-eslint over a syntax-only linter (D-115).
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { promise, security },
    rules: {
      ...promise.configs.recommended.rules,
      ...security.configs.recommended.rules,

      // Flags every computed property access, including exhaustive lookups on
      // a typed key union where the index cannot be attacker-controlled. Left on
      // it produces constant noise, and noise is how a real finding gets
      // scrolled past. The genuine risk it targets, untrusted input reaching a
      // property path, is covered by validating every external input against a
      // schema at the boundary (section 19).
      'security/detect-object-injection': 'off',

      // An unawaited promise in a worker silently drops inventory work.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      // Section 19: never let a secret reach a log or a thrown string.
      'no-console': ['error', { allow: ['warn', 'error'] }],

      // Section 19: configuration is validated in one place so it cannot be
      // half-validated in ten. This restricts reading the environment, not the
      // process object: an entrypoint still needs process.on for signals and
      // process.exitCode to fail a deployment, and banning those outright only
      // produced a disable comment on every signal handler.
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message:
            'Import the validated config from @eim/config instead of reading process.env directly.',
        },
      ],
    },
  },

  // The config package is the one place allowed to read process.env, because it
  // is what turns the raw environment into a validated typed object. It also
  // reads operator-supplied paths by design, which is what the non-literal
  // filename rule exists to flag.
  {
    files: [
      'packages/config/**/*.ts',
      '**/*.config.{ts,mts}',
      'scripts/**/*.ts',
      // The migration loader reads a directory of SQL files by design. That is
      // exactly what the non-literal-filename rule exists to flag, and here the
      // path is derived from this module's own location, never from input.
      'packages/db/src/migrations.ts',
      // The test harness reads EIM_TEST_DATABASE_URL and creates scratch
      // databases; it is not a production path.
      'packages/testing/**/*.ts',
      // The M5 exit gate reads this repository's own configuration and
      // migrations to assert that no automatic publication path exists.
      // Section 36 asks it to prove an absence, and an absence can only be
      // checked against the files that would have to contain it. The paths are
      // derived from this module's own location, never from input.
      'packages/listings/src/acceptance.integration.test.ts',
    ],
    rules: {
      'no-restricted-properties': 'off',
      'security/detect-non-literal-fs-filename': 'off',
    },
  },

  // Cryptography: node:crypto and nothing else. A dependency here would widen
  // the trust boundary around key material and authentication secrets, and the
  // package is deliberately small enough to be read in full before trusting it.
  {
    files: ['packages/crypto/**/*.ts'],
    rules: restrict([
      { group: ['next', 'next/*'], message: 'Framework imports are not allowed here.' },
      { group: ['react', 'react-dom'], message: 'UI imports are not allowed here.' },
      {
        group: ['pg', 'drizzle-orm', 'drizzle-orm/*', '@eim/db', '@eim/db/*'],
        message: 'Cryptography must not depend on persistence.',
      },
      {
        group: ['node:fs', 'node:fs/*', 'node:net', 'node:http', 'node:https'],
        message: 'Direct I/O is not allowed here.',
      },
    ]),
  },

  // Canonical domain: pure calculation only.
  {
    files: ['packages/domain/**/*.ts', 'packages/authz/**/*.ts'],
    rules: restrict([
      ...FRAMEWORK_AND_IO,
      { group: ['@eim/db', '@eim/db/*'], message: 'The domain must not depend on persistence.' },
      {
        group: ['@eim/providers', '@eim/providers/*'],
        message: 'The domain must not depend on provider transport.',
      },
      { group: ['@eim/ui', '@eim/ui/*'], message: 'The domain must not depend on UI.' },
    ]),
  },

  // Provider adapters normalize observations and commands. They do not own
  // inventory policy and must not reach into persistence (section 34).
  {
    files: ['packages/providers/**/*.ts'],
    rules: restrict([
      { group: ['next', 'next/*'], message: 'Framework imports are not allowed here.' },
      { group: ['react', 'react-dom'], message: 'UI imports are not allowed here.' },
      { group: ['@eim/db', '@eim/db/*'], message: 'Adapters must not depend on persistence.' },
    ]),
  },

  // Persistence must not depend on transport or UI.
  {
    files: ['packages/db/**/*.ts'],
    rules: restrict([
      { group: ['next', 'next/*'], message: 'Framework imports are not allowed here.' },
      { group: ['react', 'react-dom'], message: 'UI imports are not allowed here.' },
      {
        group: ['@eim/providers', '@eim/providers/*'],
        message: 'Persistence must not depend on provider transport.',
      },
    ]),
  },

  // The worker never calls the web tier over loopback HTTP (D-049), and never
  // carries out an operation a person was supposed to confirm.
  {
    files: ['apps/worker/**/*.ts'],
    rules: restrict([
      { group: ['next', 'next/*'], message: 'The worker must not import the web framework.' },
      { group: ['react', 'react-dom'], message: 'The worker has no UI.' },
      NO_REVIEWED_OPERATIONS,
    ]),
  },

  // The automatic synchronization tier, for the same reason.
  {
    files: ['packages/sync/**/*.ts', 'packages/jobs/**/*.ts'],
    rules: restrict([NO_REVIEWED_OPERATIONS]),
  },

  // Web application: React, hooks, and accessibility rules.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { react, 'react-hooks': reactHooks, 'jsx-a11y': jsxA11y, '@next/next': nextPlugin },
    // Stated rather than detected. eslint-plugin-react's detection calls
    // context.getFilename(), which ESLint 10 removed, so 'detect' throws before
    // any rule runs. Stating it also skips a filesystem probe per file.
    settings: {
      react: { version: '19.2' },
      // The App Router has no pages directory. Without this the Next plugin
      // prints a warning on every run about a directory that will never exist.
      next: { rootDir: 'apps/web' },
    },
    rules: {
      ...react.configs.flat.recommended.rules,
      ...react.configs.flat['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.strict.rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  // Tests may use non-null assertions and fixtures freely; they are not
  // production paths and over-strict typing there hides real assertions.
  {
    files: ['**/*.test.ts', '**/*.test.tsx', 'packages/testing/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      'no-restricted-properties': 'off',
      'security/detect-object-injection': 'off',
    },
  },

  // Must stay last so no stylistic rule fights Prettier.
  prettier,
);
