export {
  DEFAULT_CONSUMPTION_MODE,
  DEFAULT_SAFETY_STOCK,
  defaultSettings,
  readSettings,
  updateSettings,
  type InventorySettings,
  type SettingsChange,
  type SettingsReader,
  type SettingsUpdateResult,
  type SettingsWriter,
} from './settings';

export {
  archiveLocation,
  createLocation,
  linkLocationToChannel,
  listLocations,
  readLocationAddress,
  setLocationAddress,
  unlinkLocationFromChannel,
  updateLocation,
  type ArchiveLocationResult,
  type CreateLocationInput,
  type CreateLocationResult,
  type LinkLocationResult,
  type LocationReader,
  type LocationSummary,
  type LocationWriter,
  type PostalAddress,
  type SetAddressResult,
  type UpdateLocationInput,
  type UpdateLocationResult,
} from './locations';

export {
  createCanonicalItem,
  listCanonicalItems,
  readItemBalances,
  setItemLocationSettings,
  updateCanonicalItem,
  type CanonicalItemSummary,
  type CreateItemInput,
  type CreateItemResult,
  type ItemLocationSettings,
  type ItemReader,
  type ItemWriter,
  type ResolvedItemLocation,
  type SetItemLocationResult,
  type UpdateItemInput,
  type UpdateItemResult,
} from './items';

export {
  lockBalances,
  lockOrder,
  postMovements,
  readReversals,
  readTimeline,
  transactionally,
  type BalanceKey,
  type LedgerReader,
  type LedgerTransaction,
  type Movement,
  type PostingInput,
  type PostingResult,
  type ResultingBalance,
  type Shortfall,
} from './ledger';

export {
  applyAdjustment,
  previewAdjustment,
  reverseEntry,
  transferStock,
  type AdjustmentDatabase,
  type AdjustmentInput,
  type AdjustmentPreview,
  type AdjustmentResult,
  type PreviewResult,
  type QuantityChange,
  type ReversalResult,
  type TransferInput,
  type TransferResult,
} from './adjustments';

export {
  approveMapping,
  archiveMapping,
  proposeMapping,
  readLiveMappings,
  readMapping,
  readMappingHistory,
  readMappingsForItem,
  reviseMapping,
  type ApproveMappingResult,
  type ArchiveMappingResult,
  type MappingDatabase,
  type MappingReader,
  type MappingSummary,
  type ProposeMappingInput,
  type ProposeMappingResult,
  type ReviseMappingInput,
  type ReviseMappingResult,
} from './mappings';

export { isCheckViolation, isUniqueViolation } from './errors';
