import { createHash, createHmac, hkdfSync, timingSafeEqual } from 'node:crypto';

/**
 * Keyed hashing for authentication material (sections 19 and 20).
 *
 * Section 20 stores "only a keyed hash" of every magic-link token, email code,
 * session token, recovery code, and trusted-device token. Keyed, not plain,
 * because of the eight-digit code: its space is 100 million values, which a
 * plain SHA-256 column would let an attacker with a stolen database exhaust in
 * seconds on a laptop. The key lives in `EIM_SESSION_SECRET` on the deployment
 * host, so a database copy alone is not enough to test a guess.
 *
 * Not a password hash. Argon2 and bcrypt are for low-entropy human-chosen
 * secrets, and every value hashed here is generated by `tokens.ts` with at least
 * 128 bits of entropy, where the deliberate slowness would buy nothing and would
 * be paid on every request.
 */

/**
 * What a hash is for.
 *
 * Each domain derives its own subkey, so a value is only ever valid for the
 * purpose it was issued under. Without this, the hash of a trusted-device token
 * and the hash of a session token would be the same bytes, and a read of one
 * table would be a forgery in another.
 */
export type HashDomain =
  | 'session'
  | 'browser_binding'
  | 'pending_authentication'
  | 'magic_link'
  | 'email_code'
  | 'recovery_code'
  | 'trusted_device'
  | 'passkey_challenge'
  | 'setup_secret'
  | 'invitation'
  /** Section 19: routine logs identify an address by fingerprint, not by value. */
  | 'email_fingerprint'
  /** Sections 13, 14: the single-use state carried through a provider's consent screen. */
  | 'connection_authorization'
  /**
   * Section 13: the verification token a notification destination was
   * registered with. Stored as a fingerprint so that a token the operator
   * changed in the provider's portal is detectable, without the destination row
   * becoming a second place the token itself lives.
   */
  | 'notification_verification'
  /**
   * Section 5: the emailed confirmation that a business really is to be
   * deleted. Its own domain rather than reusing `invitation`, so a token issued
   * for one purpose can never be presented for the other — the two have very
   * different consequences and identical shapes.
   */
  | 'business_deletion';

export interface KeyedHasher {
  /**
   * Hashes `value` for `domain`.
   *
   * `binding` ties the result to a specific record — the challenge id for an
   * email code, the user id for a recovery code. Two challenges that happen to
   * generate the same eight digits therefore store different hashes, so a
   * database reader cannot tell that they matched, and a code observed for one
   * challenge cannot be replayed against another.
   */
  hash(domain: HashDomain, value: string, binding?: string): string;
  /** Constant-time comparison of a presented value against a stored hash. */
  verify(domain: HashDomain, value: string, storedHash: string, binding?: string): boolean;
}

/**
 * Fixed salt for subkey derivation.
 *
 * A constant, and correctly so: HKDF's salt is a domain separator, not a
 * per-value salt, and the per-purpose separation this needs comes from `info`.
 * Making it vary would change every stored hash on every restart.
 */
const HKDF_SALT = Buffer.from('eim-auth-hash-v1', 'utf8');

export function createHasher(secret: string): KeyedHasher {
  if (secret.length < 32) {
    throw new Error('The hashing secret must be at least 32 characters (EIM_SESSION_SECRET).');
  }

  // HKDF costs a hash per call, and these run on every authenticated request.
  // The subkey depends only on the domain, so it is derived once.
  const subkeys = new Map<HashDomain, Buffer>();

  const subkeyFor = (domain: HashDomain): Buffer => {
    const existing = subkeys.get(domain);

    if (existing !== undefined) {
      return existing;
    }

    const derived = Buffer.from(
      hkdfSync('sha256', Buffer.from(secret, 'utf8'), HKDF_SALT, Buffer.from(domain, 'utf8'), 32),
    );

    subkeys.set(domain, derived);
    return derived;
  };

  return {
    hash(domain, value, binding) {
      return createHmac('sha256', subkeyFor(domain))
        .update(lengthPrefixed(binding ?? '', value))
        .digest('hex');
    },

    verify(domain, value, storedHash, binding) {
      return constantTimeEqual(this.hash(domain, value, binding), storedHash);
    },
  };
}

/**
 * Compares two strings without leaking where they differ, or how long they are.
 *
 * `timingSafeEqual` throws on a length mismatch, which is itself a signal, so
 * both sides are hashed to a fixed width first. That is safe here because the
 * inputs are already hashes or high-entropy tokens: digesting them is not
 * weakening anything.
 */
export function constantTimeEqual(a: string, b: string): boolean {
  const left = createHash('sha256').update(a, 'utf8').digest();
  const right = createHash('sha256').update(b, 'utf8').digest();

  return timingSafeEqual(left, right);
}

function lengthPrefixed(...fields: readonly string[]): string {
  return fields.map((field) => `${String(Buffer.byteLength(field, 'utf8'))}:${field}`).join('');
}
